[package]
name = "chacha20"
description = "chacha20_poly1305 encryption tool"
version = "0.1.0"
authors = ["Avril <flanchan@cumallover.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13"
getrandom = "0.2"
openssl = "0.10"
smallvec = {version = "1.6.1", features=["write", "union"]}


[dev-dependencies]
#khash = {version = "2.0.4", default-features=false}
